# 1. 파이썬에서의 벡터
>- 가장 쉽게 표현하는 방법은 list로 표현하는 방법이다.

In [1]:
a = [1, 2, 3]

In [2]:
height_weight_age = [
    180, # 키
    73,  # 몸무게
    40   # 나이
]

# 2. 파이썬 list는 벡터 연산이 가능한가?
>- 파이썬의 list는 실제로 벡터가 아니므로, 벡터 연산이 불가능하다.
    - list가 벡터 연산이 되도록 하기 위해서는 따로 작업을 해줘야한다.
- 벡터 연산 ?
    - 각 벡터 상에서 같은 위치에 있는 성분끼리 연산하는 것. ( element-wise 연산 )
    - ex. [1, 2] + [2, 1] = [1 + 2, 2 + 1]
    - 두 벡터의 길이가 다르다면 연산이 불가능하다.
    - 파이썬에서 벡터 연산을 하기 위해서는 Numpy 를 사용한다.

# 3. Numpy
- C와 fotran으로 짜여진 파이썬 배열연산 패키지 (매우 빠름)
    - 모든 머신러닝, 딥러닝 알고리즘에 활용되고 있고, numpy 이후부터 python이 과학계산에 널리 사용되었음.

In [3]:
import numpy as np

In [4]:
# array creation

a_arr = np.array([1, 2, 3])
b_arr = np.array([2, 3, 4])

a_list = [1, 2, 3]
b_list = [2, 3, 4]

In [5]:
a_arr

array([1, 2, 3])

In [6]:
a_list

[1, 2, 3]

# 4. 벡터 연산

## (1) 벡터 덧셈
> ### pure python
> - 벡터 덧셈은 zip을 사용해서 두 벡터를 묶은 뒤, 두 배열의 각 성분끼리 더하는 list comprehension을 적용한다.

In [7]:
list(zip(a_list, b_list))

[(1, 2), (2, 3), (3, 4)]

In [8]:
def vector_add(v, w):
    """각 성분끼리 더한다."""
    return [v_i + w_i for v_i, w_i in zip(v, w)]

In [9]:
vector_add(a_list, b_list)

[3, 5, 7]

In [10]:
a_arr + b_arr

array([3, 5, 7])

In [11]:
def vector_subtract(v, w):
    """각 성분끼리 뺀다."""
    return [v_i - w_i for v_i, w_i in zip(v, w)]

In [14]:
def vector_sum(vectors):
    """모든 벡터의 각 성분들끼리 더한다."""
    result = vectors[0]
    for vector in vectors[1:]:
        result = vector_add(result, vector)
    return result

In [15]:
vector_sum([[1, 2, 3], [1, 2, 3], [1, 2, 3]])

[3, 6, 9]

> ### numpy

In [17]:
## 덧셈

a_arr + b_arr

array([3, 5, 7])

In [18]:
## 뺄셈

a_arr - b_arr

array([-1, -1, -1])

## (2) 스칼라 곱
> ### pure python

In [19]:
def scalar_multiply(c, v):
    """c는 숫자, v는 벡터"""
    return [c * v_i for v_i in v]

In [20]:
scalar_multiply(5, [1, 2, 3])

[5, 10, 15]

> ### numpy

In [22]:
5 * a_arr

array([ 5, 10, 15])

## (3) 벡터 내적
> ### pure python

In [23]:
## zip을 사용해서 두 벡터를 묶은 뒤, 두 배열의 각 성분끼리 곱하는 list comprehension을 적용하고, 마지막 결과를 모두 더해준다.

def dot(v, w):
    """v_1*w_1 + v_2*w_2 + ..."""
    return sum(v_i * w_i for v_i, w_i in zip(v, w))

In [24]:
dot(a_list, b_list)

20

> ### numpy

In [25]:
## 곱셈 (내적이 아님)

a_arr * b_arr

array([ 2,  6, 12])

In [26]:
## 내적 1

a_arr.dot(b_arr)

20

In [27]:
## 내적 2

np.dot(a_arr,b_arr)

20

## (4) 벡터 크기
> ### pure python

In [28]:
def sum_of_squares(v):
    """v_1*v_1 + v_2*v_2 + ... + v_n*v_n"""
    return dot(v, v)

In [31]:
def magnitude(v):
    import math
    return math.sqrt(sum_of_squares(v))
#     return sum_of_squares(v)**(1/2)


In [32]:
magnitude(a_list)

3.7416573867739413

> ### numpy

In [33]:
## 벡터 크기

np.linalg.norm(a_arr)

3.7416573867739413

# 5. 행렬

> ### pure python

In [35]:
## 행렬을 list로 표현

A = [[1, 2, 3], 
     [4, 5, 6]]

B = [[1, 2], 
     [3, 4],
     [5, 6]]

In [36]:
## 행렬의 shape를 확인하는 함수 (n, m)

def shape(A):
    num_rows = len(A)
    num_cols = len(A[0]) if A else 0 ## A의 첫번째 행의 element의 갯수
    return num_rows, num_cols

In [ ]:
# A = 2x3, B = 3x2

> ### numpy

In [39]:
matrix_a = np.array([[1, 2, 3], [2, 3, 4]])
matrix_b = np.array([[10, 20, 30], [20, 30, 40]])

In [40]:
## 행렬 shape

matrix_a.shape

(2, 3)

In [41]:
mat_a = [[1, 2, 3], [2, 3, 4]]

In [43]:
## 행렬 slicing
## 행 선택

matrix_a[1]

array([2, 3, 4])

In [44]:
matrix_a

array([[1, 2, 3],
       [2, 3, 4]])

In [46]:
## 2행의 2번째 열까지

matrix_a[1, :2]

array([2, 3])

In [47]:
## 모든 행의 2번째 열까지
matrix_a[:, :2]

array([[1, 2],
       [2, 3]])

In [48]:
## 전치 행렬

matrix_a.T

array([[1, 2],
       [2, 3],
       [3, 4]])

In [49]:
matrix_a

array([[1, 2, 3],
       [2, 3, 4]])

In [50]:
## 행렬곱

np.dot(matrix_a, matrix_b)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [51]:
## 행렬의 내적을 위해서는 곱이 가능한 shape으로 바꾸어 주어야된다.

np.dot(matrix_a.T, matrix_b)

array([[ 50,  80, 110],
       [ 80, 130, 180],
       [110, 180, 250]])

# 보충자료
> - numpy tutorial
    - https://docs.scipy.org/doc/numpy/user/quickstart.html
-  Matlab 사용자를 위한 numpy
    - https://docs.scipy.org/doc/numpy-1.13.0/user/numpy-for-matlab-users.html
- numpy tutorial 한글버전
    - python 2.7로 작성되어있어서 python3.x 에서는 작동하지 않는 코드도 있음.
        - print "object" 형태를 print("object") 형태로만 바꿔주면 된다.
    - http://ishuca.tistory.com/373