In [1]:
import numpy as np # 배열연산 패키지 호출

In [2]:
## 사용할 기본 데이터

num_friends = [100,49,41,40,25,21,21,19,19,18,18,16,15,15,15,15,14,14,13,13,13,13,12,12,11,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,8,8,8,8,8,8,8,8,8,8,8,8,8,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]
daily_minutes = [1,68.77,51.25,52.08,38.36,44.54,57.13,51.4,41.42,31.22,34.76,54.01,38.79,47.59,49.1,27.66,41.03,36.73,48.65,28.12,46.62,35.57,32.98,35,26.07,23.77,39.73,40.57,31.65,31.21,36.32,20.45,21.93,26.02,27.34,23.49,46.94,30.5,33.8,24.23,21.4,27.94,32.24,40.57,25.07,19.42,22.39,18.42,46.96,23.72,26.41,26.97,36.76,40.32,35.02,29.47,30.2,31,38.11,38.18,36.31,21.03,30.86,36.07,28.66,29.08,37.28,15.28,24.17,22.31,30.17,25.53,19.85,35.37,44.6,17.23,13.47,26.33,35.02,32.09,24.81,19.33,28.77,24.26,31.98,25.73,24.86,16.28,34.51,15.23,39.72,40.8,26.06,35.76,34.76,16.13,44.04,18.03,19.65,32.62,35.59,39.43,14.18,35.24,40.13,41.82,35.45,36.07,43.67,24.61,20.9,21.9,18.79,27.61,27.21,26.61,29.77,20.59,27.53,13.82,33.2,25,33.1,36.65,18.63,14.87,22.2,36.81,25.53,24.62,26.25,18.21,28.08,19.42,29.79,32.8,35.99,28.32,27.79,35.88,29.06,36.28,14.1,36.63,37.49,26.9,18.58,38.48,24.48,18.95,33.55,14.24,29.04,32.51,25.63,22.22,19,32.73,15.16,13.9,27.2,32.01,29.27,33,13.74,20.42,27.32,18.23,35.35,28.48,9.08,24.62,20.12,35.26,19.92,31.02,16.49,12.16,30.7,31.22,34.65,13.13,27.51,33.2,31.57,14.1,33.42,17.44,10.12,24.42,9.82,23.39,30.93,15.03,21.67,31.09,33.29,22.61,26.89,23.48,8.38,27.81,32.35,23.84]

num_friends = np.array(num_friends) # 파이썬 list를 numpy array로 변환
daily_minutes = np.array(daily_minutes)

# 통계

# 1. 평균

### $ \bar{x} = \frac{1}{N} \sum_{i=1}^{N}x_i $



- 가지고 있는 각 데이터를 모두 더하고 ($ \sum_{i=1}^{N}x_i $ ), 전체 데이터의 개수로 나눠준다. ($\frac{1}{N}$)

In [3]:
def mean(x):
    return sum(x) / len(x)

In [4]:
mean(num_friends)

7.333333333333333

In [5]:
## numpy

np.mean(num_friends)

7.333333333333333

# 2. 중앙값
- 전체 데이터를 크기 순으로 정렬했을 때 가장 가운데 있는 값

In [6]:
def median(v):
    """v의 중앙값을 계산"""
    n = len(v)
    sorted_v = sorted(v)
    midpoint = n // 2
    
    if n % 2 == 1:
        # 데이터 포인트의 개수가 홀수면 중앙값을 반환
        return sorted_v[midpoint]
    
    else:
        # 데이터 포인트의 개수가 짝수면 두 중앙값의 평균을 반환
        lo = midpoint - 1
        hi = midpoint
        return (sorted_v[lo] + sorted_v[hi])/2

In [7]:
median(num_friends)

6.0

In [8]:
## numpy

np.median(num_friends)

6.0

### 평균 vs 중앙값
> - 평균이 중앙값보다 계산하기 간편하다.
- 평균은 데이터가 바뀌어도 값의 변화가 중앙값보다 더 부드럽다.
- 평균은 이상치에 매우 민감하다.

In [9]:
# 1 ~ 10까지의 정수에서 이상치가 추가되었을 때
ex_data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1000])

In [10]:
print('평균 : ', ex_data.mean())
print('중앙값 : ', np.median(ex_data))

평균 :  95.9090909090909
중앙값 :  6.0


# 3. 분산

### $ s^2 = \frac{1}{N} \sum_{i=1}^{N}(x_i - \bar{x})^2$

- 각 데이터와 전체 데이터의 평균과의 차이의 제곱을 모두 더하고 ( $\sum_{i=1}^{N}(x_i - \bar{x})^2$), 전체 데이터의 개수로 나눠준다. ($\frac{1}{N}$)
    - 편차 제곱의 평균
    

In [11]:
def de_mean(x):
    x_bar = mean(x)
    return x - x_bar # 데이터 x와 평균의 차이 ( 배열 연산이므로 x (벡터, 배열) - x_bar (스칼라) 은 배열이다.)

In [12]:
def variance(x):
    n = len(x)
    deviations = de_mean(x)
    deviations.dot(deviations)
    return deviations.dot(deviations) / (n)

In [13]:
variance(num_friends)

81.1437908496732

In [14]:
# [2, 4, 6, 8, 10, 12, 14] 의 분산을 구해보세요 (손으로)

# 4. 표준편차

### $ s = \sqrt(\frac{1}{N} \sum_{i=1}^{N}(x_i - \bar{x})^2)$

- 분산의 제곱근

In [15]:
def standard_deviation(x):
    import math
    return math.sqrt(variance(x))

In [16]:
standard_deviation(num_friends)

9.00798483844601

In [17]:
## numpy

np.var(num_friends), np.std(num_friends)

(81.14379084967321, 9.007984838446012)

In [ ]:
# [2, 4, 6, 8, 10, 12, 14] 의 표준편차를 구해보세요 (손으로)

# 4. 공분산
- 평균을 중심으로 각 자료들이 어떻게 분포되어 있는지 크기와 방향성을 같이 보여준다

- ### $s_{xy} = \frac {1} {N} \sum _{ i=1 }^{N }{ (x_i-m_x)(y_i-m_y) } $
    - 위 공식을 벡터로 표현하면 아래와 같이 나타낼 수 있다. ( $\sum _{ i=1 }^{N }{ (x_i-m_x)(y_i-m_y) }$ = 두 벡터의 내적 )
    - ### $Cov(X, Y) = \frac {1} {N} (X-\bar{X})(Y-\bar{Y}) $

- 각 데이터의 평균과의 편차를 같은 위치에 있는 편차끼리 곱하고 더한 값 ($\sum _{ i=1 }^{N }{ (x_i-m_x)(y_i-m_y) }$)을 데이터의 개수로 나눠준다. ($\frac {1} {N}$)

In [19]:
def covariance(x, y):
    n = len(x)
    return np.dot(de_mean(x), de_mean(y)) / n

In [20]:
covariance(num_friends, daily_minutes)

22.31550653594771

In [21]:
## numpy 
## [[var_num_frends, cov]
## [cov, var_daily_minutes]]

np.cov(num_friends, daily_minutes)

array([[ 81.54351396,  22.42543514],
       [ 22.42543514, 100.78589895]])

In [22]:
# [2, 4, 6, 8, 10, 12, 14], [13, 11, 9, 7, 5, 3, 1] 두 자료의 공분산을 구해보세요.

In [23]:
d1 = np.array([2, 4, 6, 8, 10, 12, 14])
d2 = np.array([13, 11, 9, 7, 5, 3, 1])

np.cov(d1, d2)

array([[ 18.66666667, -18.66666667],
       [-18.66666667,  18.66666667]])

# 5. 상관관계
- 공분산에서 방향성만 분리한 값이다.

In [27]:
# 데이터를 표준편차로 나눠준다면 벌어지는 일

raw_data = np.array([2, 4, 6, 8])
raw_data_std = np.array([2, 4, 6, 8]).std()
raw_data_normalized = (raw_data/raw_data_std)

In [29]:
print('Before : ', raw_data_std)
print('After : ', raw_data_normalized.std())

Before :  2.23606797749979
After :  1.0


- ### $r_{xy} = \frac {s_{xy}} {\sqrt{s_x^2 \bullet s_y^2}} $
    - 표준편차로 나눠버리면 -1, 1 사이의 값으로 만들어준다.
    - scale이 다른 데이터들의 상관관계를 비교하기가 아주 좋아진다.
    
- -1 <= $r_{xy}$ <= 1
    

In [30]:
d1 = np.array([2, 4, 6, 8])
d2 = np.array([7, 5, 3, 1])

In [31]:
np.cov(d1, d2)

array([[ 6.66666667, -6.66666667],
       [-6.66666667,  6.66666667]])

In [32]:
d100 = np.array([2, 4, 6, 8])*100
d200 = np.array([7, 5, 3, 1])*100

In [33]:
np.cov(d100, d200)

array([[ 66666.66666667, -66666.66666667],
       [-66666.66666667,  66666.66666667]])

- 상관관계를 이용하면 서로 scale이 다른 두 자료의 방향성을 비교할 수 있다.

In [34]:
np.corrcoef(d1, d2)[0][1], np.corrcoef(d100, d200)[0][1]

(-1.0, -1.0)

In [35]:
def correlation(x, y):
    stdev_x = standard_deviation(x)
    stdev_y = standard_deviation(y)
    if stdev_x > 0 and stdev_y > 0:
        return covariance(x, y) / stdev_x / stdev_y
    else:
        return 0

In [36]:
correlation(num_friends, daily_minutes)

0.24736957366478224

In [37]:
## numpy 

import numpy as np
np.corrcoef(num_friends,daily_minutes)[0][1]

0.24736957366478227

In [ ]:
# [2, 4, 6, 8, 10, 12, 14], [13, 11, 9, 7, 5, 3, 1] 두 자료의 상관관계를 구해보세요.

In [39]:
d1 = np.array([2, 4, 6, 8, 10, 12, 14])
d2 = np.array([13, 11, 9, 7, 5, 3, 1])

correlation(d1, d2)

-1.0

### 상관관계 해석시 주의 사항
> - 상관관계가 0이라는 것은 두 변수 사이에 선형적인 관계가 없다는 것만을 의미한다.
- 상관관계가 인과관계를 말하지 않는다.
    - 인과관계를 밝혀 내는 일은 많은 노력과 시간이 소요되는 일이므로, 상관관계를 통해 빠르게 확인하고 의사결정을 하는 편이 더 낫다.

# 판다스를 활용한 상관 분석

In [40]:
import pandas as pd
from sklearn.datasets import load_boston

boston = load_boston()

In [43]:
df = pd.DataFrame(boston.data, columns=boston.feature_names)
df.loc[:, 'House_Price'] = boston.target

In [48]:
df.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     3.593761   11.363636   11.136779    0.069170    0.554695    6.284634   
std      8.596783   23.322453    6.860353    0.253994    0.115878    0.702617   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.885500   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208500   
75%      3.647423   12.500000   18.100000    0.000000    0.624000    6.623500   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT  House_Price  
count  506.000000   506.000000  
mean    12.653063    22.532806  
std      7.141062     9.197104  
min      1.730000     5.000000  
25%      6.950000    17.025000  
50%     11.360000    21.200000  
75%     16.955000    25.000000  
max     37.970000    50.000000